service: traffic-collissions-data-pipeline

provider:
  name: aws
  runtime: python3.7
  profile: zoning
  timeout: 300
  environment:
    GOOGLE_MAPS_KEY: ""

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: true
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: false

functions:
  traffic_collissions:
    handler: handler.traffic_collissions
    events:
      - schedule:
        name: traffic-collissions-schedule
        description: 'Schedule for Traffic Collissions updates'
        rate: cron(0 2 * * ? *)
  geocode_c_by_year:
    handler: handler.geocode_collissions_by_year
  geocode_collissions:
    handler: handler.geocode_collissions
    events:
      - schedule:
        name: traffic-collissions-geocode-schedule
        description: 'Schedule for Traffic Collissions updates'
        rate: cron(30 2 * * ? *)
  tweet_collissions:
    handler: handler.tweet_fatality
    events:
      - schedule:
        name: traffic-collissions-fatality-schedule
        description: 'Schedule for Traffic Collissions updates'
        rate: cron(0 6 * * ? *)
